const { MigrationInterface, QueryRunner } = require("typeorm");

module.exports = class Initdb1744281767028 {
    name = 'Initdb1744281767028'

    async up(queryRunner) {
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "message" character varying NOT NULL, "order_id" character varying NOT NULL, "piority" character varying NOT NULL, "shop_id" character varying NOT NULL, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "shop_id" character varying NOT NULL, "coupon_code" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'discount', "coupon_value" integer NOT NULL, "payment_method" character varying, "product_id" character varying, "max_use" integer NOT NULL DEFAULT '1', "total_usage" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "main_color" character varying NOT NULL DEFAULT '#7367f0', "hero_svg" character varying, "storeId" uuid NOT NULL, CONSTRAINT "REL_d8c8d1a477d1a0b3dacde775d7" UNIQUE ("storeId"), CONSTRAINT "PK_1094f3ba73221bde3ec26d2a522" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "storename" character varying NOT NULL, "domain_name" character varying DEFAULT 'sellit.app', "hero_text" text, "user_type" character varying NOT NULL DEFAULT 'shop_admin', "email" character varying NOT NULL, "parent_store" character varying, "telephone" character varying, "display_picture" character varying, "active" boolean NOT NULL DEFAULT false, "token" character varying, "discord_link" character varying, "stripe_key" character varying, "coinbase_key" character varying, "password" character varying NOT NULL, "salt" character varying NOT NULL, "permissions" text NOT NULL DEFAULT '["product:read","product:delete","payment:create","coupon:read"]', "customizationId" character varying, CONSTRAINT "UQ_18be40798131ed84f661865416a" UNIQUE ("storename"), CONSTRAINT "UQ_13be324e4ad3ea7ec1499899f98" UNIQUE ("domain_name"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "shop_id" character varying NOT NULL, "category_name" character varying NOT NULL, "category_postion" integer NOT NULL DEFAULT '1', "shop_name" character varying NOT NULL, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying, "image_src" character varying DEFAULT '/imgs/products/attachment.png', "items" text, "stock" integer NOT NULL DEFAULT '0', "unlisted" boolean NOT NULL DEFAULT false, "paypal" boolean NOT NULL DEFAULT false, "stripe" boolean NOT NULL DEFAULT false, "coinbase_key" boolean NOT NULL DEFAULT false, "cashapp" boolean NOT NULL DEFAULT false, "private_mode" boolean NOT NULL DEFAULT false, "warranty" boolean NOT NULL DEFAULT false, "warranty_msg" character varying, "enable_youtube" boolean NOT NULL DEFAULT false, "video_url" character varying, "product_type" character varying NOT NULL DEFAULT 'serial', "seller_message" character varying NOT NULL DEFAULT 'Thank You for Your Interest in Our Products!', "amount" real NOT NULL DEFAULT '0', "service_info" character varying, "max_purchase" integer NOT NULL DEFAULT '10', "min_purchase" integer NOT NULL DEFAULT '1', "webhook_url" character varying, "callback_url" character varying, "shop_id" uuid NOT NULL, "categoryid" uuid, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "admin_id" character varying NOT NULL, "email" character varying NOT NULL, "private_key" character varying, "password" character varying NOT NULL, CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blacklists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "data" character varying NOT NULL, "note" character varying, "shop_id" character varying NOT NULL, CONSTRAINT "PK_69894f41b74b226aae9ea763bc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastChanged_by" character varying(300), "deleted_at" TIMESTAMP, "deleted_by" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "qty" character varying NOT NULL, "total_amount" real NOT NULL DEFAULT '0', "order_status" character varying NOT NULL DEFAULT 'unpaid', "order_from" character varying NOT NULL, "payment_gateway" character varying NOT NULL, "items" text, "platform_fee" character varying NOT NULL DEFAULT '0', "productid" uuid NOT NULL, "shop_id" uuid NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "customizations" ADD CONSTRAINT "FK_d8c8d1a477d1a0b3dacde775d7b" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9e952e93f369f16e27dd786c33f" FOREIGN KEY ("shop_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_a5a1cf7dc103ccc33b70284be88" FOREIGN KEY ("categoryid") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_34bb1ddc1931a051eeb28694386" FOREIGN KEY ("productid") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_33f20db82908f7685a5c0c58ac6" FOREIGN KEY ("shop_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    async down(queryRunner) {
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_33f20db82908f7685a5c0c58ac6"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_34bb1ddc1931a051eeb28694386"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_a5a1cf7dc103ccc33b70284be88"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9e952e93f369f16e27dd786c33f"`);
        await queryRunner.query(`ALTER TABLE "customizations" DROP CONSTRAINT "FK_d8c8d1a477d1a0b3dacde775d7b"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "blacklists"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TABLE "customizations"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
    }
}
